# PARTLY SUPERSEDED (M3 phase 1b, tools/xml1build/SPEC.md 27.7): the XML1 half (names_xml1.json, the char/ aliases
# of prepare P4) is regenerated by prepare stage P2 (tools/xml1build/prepare/tables.py, names_xml1(): the same
# candidates, taken in sorted order, where this script iterated a set whose order followed PYTHONHASHSEED). The
# XML2 half and the coverage figures stay research. Builds never run this script.
"""
Model the engines' sound-name -> key mapping and measure how many bank keys it explains, per bank, for both games.
Name sources: every attribute value / script string in each game's data (soundrefs_*.json raw pools rebuilt here),
plus string literals from the executables. Name transformations modelled (from XMen2.exe 0x590bd0 / 0x590e50 and
XML1 xbe strings):
  * zone prefix: names starting with 'death_style' (XML2 compares 11 chars) or 'zone_sh' (7 chars) get
    '<zone soundfile>/' prepended; XML1 xbe has the literals 'death_styles' and 'zone_shared'.
  * random variants: key = hash('/***RANDOM***/<n>', seed=hash(name))
  * character sounds: '<char prefix>/<sounddir>/<event>' ; XML1 prefix 'character/', XML2 'char/'
  * music: 'music/<bank>_a' 'music/<bank>_c'
Writes names_<game>.json : {bank_relpath: {key_hex: name}} and prints coverage.
"""
import os as _os  # public export: the repo root and the XML2 install instead of the author's absolute paths
_REPO = _os.path.abspath(__file__).replace('\\', '/').rsplit('/research/', 1)[0]
_XML2 = (_os.environ.get('XML2_DIR') or 'X-Men Legends II').replace('\\', '/')
import os, re, sys, json, collections
import zsnd
from zhash import elf_hash
from soundrefs import collect, BANKS

OUT = _REPO + '/research/sound'
EXES = {'xml2': _XML2 + '/XMen2.exe', 'xml1': _REPO + '/xml1_xbox/default.xbe'}
CHARPFX = {'xml1': 'character/', 'xml2': 'char/'}


def exe_strings(path):
    d = open(path, 'rb').read()
    for m in re.finditer(rb'[\x20-\x7e]{4,}', d):
        s = m.group().decode()
        if re.fullmatch(r'[a-z0-9_]+(/[a-z0-9_%]+)+', s.lower()):
            yield s.lower()


def main(games=('xml2', 'xml1')):
    for game in games:
        refs, scripts = collect(game)
        pool = set()
        for f, tag, k, v in refs + scripts:
            if v and len(v) < 120 and not re.fullmatch(r'[-0-9. ]+', v):
                pool.add(v.replace('\\', '/').lower().strip())
        pool |= set(exe_strings(EXES[game]))
        # event vocabulary: tails of multi-component names
        events = set(n for n in pool if re.fullmatch(r'[a-z0-9_]{2,32}', n))  # single tokens (e.g. SOUNDTABLE values)
        for n in pool:
            parts = n.split('/')
            if len(parts) >= 2:
                events.add(parts[-1])
                if len(parts) >= 3:
                    events.add('/'.join(parts[2:]))
        root = BANKS[game]
        result = {}
        cov = []
        for p in zsnd.iter_banks(root):
            b = zsnd.load(p, strict=False)
            rel = os.path.relpath(p, root).replace('\\', '/')
            base = os.path.basename(p).rsplit('.', 1)[0]
            zone = base.rsplit('_', 1)[0] if re.search(r'_[acdmv]$', base) else base
            keys = {}
            for s in b.sounds:
                for h in s.hashes:
                    keys[h] = 'sound'
            for t in b.tracks:
                for h in t.hashes:
                    keys[h] = 'track'
            if not keys:
                continue
            cands = set(pool)
            for n in pool:
                if n.startswith('death_style') or n.startswith('zone_sh'):
                    cands.add(zone + '/' + n)
            cands.add('music/' + base)
            for pfx in (CHARPFX[game],):
                for e in events:
                    cands.add(pfx + base + '/' + e)
            names = {}
            for n in cands:
                h = elf_hash(n)
                if h in keys:
                    names[h] = n
                # random variants
                for i in range(16):
                    h2 = elf_hash('/***RANDOM***/%d' % i, h)
                    if h2 in keys:
                        names[h2] = n + '/***RANDOM***/%d' % i
                    elif i > 0:
                        break
            # sample-file-name keyed sounds (XML1 layered death-style parts)
            for f in b.files:
                fn = b.file_name(f).rsplit('.', 1)[0].lower()
                h = elf_hash(fn)
                if h in keys and h not in names:
                    names[h] = fn
            result[rel] = {'%08x' % h: n for h, n in sorted(names.items())}
            cov.append((rel, len(names), len(keys)))
        json.dump(result, open(os.path.join(OUT, 'names_%s.json' % game), 'w'), indent=1)
        tot_n = sum(c[1] for c in cov)
        tot_k = sum(c[2] for c in cov)
        print('%s: resolved %d / %d keys (%.1f%%) in %d banks' % (game, tot_n, tot_k, 100.0 * tot_n / tot_k, len(cov)))
        for rel, n, k in sorted(cov, key=lambda c: c[1] / c[2]):
            print('   %-28s %5d / %5d  %5.1f%%' % (rel, n, k, 100.0 * n / k))


if __name__ == '__main__':
    main(tuple(sys.argv[1:]) or ('xml2', 'xml1'))
